# Exported from Render on 2024-07-05T17:40:53Z
services:
- type: web
  name: pdtech
  runtime: node
  repo: https://github.com/prkmhs/strapideploy
  plan: free
  envVars:
  - key: CLOUDINARY_SECRET
    sync: false
  - key: CLOUDINARY_KEY
    sync: false
  - key: CLOUDINARY_NAME
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DATABASE_SSL
    sync: false
  - key: DATABASE_PASSWORD
    sync: false
  - key: DATABASE_USERNAME
    sync: false
  - key: DATABASE_NAME
    sync: false
  - key: DATABASE_PORT
    sync: false
  - key: DATABASE_HOST
    sync: false
  - key: DATABASE_CLIENT
    sync: false
  - key: TRANSFER_TOKEN_SALT
    sync: false
  - key: ADMIN_JWT_SECRET
    sync: false
  - key: API_TOKEN_SALT
    sync: false
  - key: APP_KEYS
    sync: false
  region: oregon
  buildCommand: npm install; npm run build
  startCommand: npm run start
version: "1"
